version: '3.3'

networks:
  brnet:
    ipam:
      config:
        - subnet: 172.21.0.0/16

services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: images/web
    networks:
      brnet:
        ipv4_address: 172.21.0.3  
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: /bin/bash -c "cd /app/frontend; npm cache clean --force && npm run build; cd /app/backend/; npm run start;"
  db:
    container_name: db
    image: mongo:latest
    networks:
      brnet:
        ipv4_address: 172.21.0.2
    ports:
     - "27777:27017"