version: '3.3'

networks:
  brnet:
    ipam:
      config:
        - subnet: 172.21.0.0/16

services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: images/web/image
    networks:
      brnet:
        ipv4_address: 172.21.0.3  
    ports:
      - "3000:3000"
    command: >
      bash -c "npm run start"

  db:
    container_name: db
    image: mongo:latest
    #build:
    #  context: ./
    #  dockerfile: images/db/image
    networks:
      brnet:
        ipv4_address: 172.21.0.2
    ports:
     - "27777:27017"
    volumes:
      - ./data:/data/db